In [1]:
# Import and run a trained model 
import numpy as np
import tensorflow.compat.v1 as tf
from sklearn.metrics import confusion_matrix
import pandas as pd

In [2]:
def get_test_batch(XTest, yTest, batchSize):
    #a generator that slices and returns batchSize of XTrain and yTrain instances from top down
    counter = 0;
    while True:
        if counter >= len(yTest):
            break;
        returnXTest = XTest[counter:counter + batchSize];
        returnYTest = yTest[counter:counter + batchSize];
        counter = counter + batchSize;
        yield returnXTest, returnYTest

In [3]:
raw_x_test = np.load('numpyData/raw_x_test.npy')
raw_y_test = np.load('numpyData/raw_y_test.npy')
y_test_dummy = np.zeros((260, 3))

batch_size = 260
latent_size = 100
sequence_length = 64
num_classes = 3

In [4]:
with tf.Session() as sess:
    saver = tf.train.import_meta_graph('savedModels/CNN/CNN_80/recall0_30recall2_68_epoch_221_SSL_GAN.ckpt.meta')
    saver.restore(sess, 'savedModels/CNN/CNN_80/recall0_30recall2_68_epoch_221_SSL_GAN.ckpt')
    
    graph = tf.get_default_graph()
    # Inputs
    input_x = graph.get_tensor_by_name('input_x:0')
    input_y = graph.get_tensor_by_name('input_y:0')
    dropout_keep_prob = graph.get_tensor_by_name('dropout_keep_prob:0')
    # Output of interest
    predictions = graph.get_tensor_by_name('output/predictions:0')
    
    test_predictions_all = []
    
    for batch_x, batch_y in get_test_batch(raw_x_test, y_test_dummy, batch_size):
        test_feed_dictionary = val_feed_dict = {
                    input_x: batch_x,
                    input_y: batch_y,
                    dropout_keep_prob: 1.0 # No dropout
                }
        test_predictions = predictions.eval(feed_dict=test_feed_dictionary)
        test_predictions_all.append(test_predictions)
        
    test_predictions_all = np.concatenate(test_predictions_all)


INFO:tensorflow:Restoring parameters from savedModels/CNN/CNN_80/recall0_30recall2_68_epoch_221_SSL_GAN.ckpt


In [5]:
test_predictions_all

array([2, 2, 2, 0, 2, 0, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2,
       0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0, 2, 2, 2, 0,
       2, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2,
       0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2,
       0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 0, 0, 2, 0, 0,
       2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0], dtype=int64)

In [6]:
#array([2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0,
 #      2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0, 2, 2, 2, 0,
  #     2, 0, 1, 0, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0,
   #    0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2,
    #   0, 1, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
     #  2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 2, 2,
      # 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 0, 2, 2, 0, 2, 2, 0,
      # 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 2, 0, 2, 0, 2, 2, 2,
      # 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2,
      # 2, 2, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0,
      # 2, 2, 1, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 0,
      # 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2], dtype=int64)

In [7]:
confusion_matrix(np.argmax(raw_y_test, axis=1), test_predictions_all)

array([[30,  0, 14,  0],
       [ 1,  0,  0,  0],
       [22,  0, 68,  0],
       [31,  0, 94,  0]], dtype=int64)

In [8]:
import pandas as pd

df = pd.read_csv('albania.csv')
label = []
for pred in test_predictions_all:
    if pred == 0:
        label.append('Building')
    if pred == 1:
        label.append('Infrastructure')
    if pred == 2:
        label.append('Resilience')

In [9]:
df

sentence       label
0    Albania’s search for quake victims ends as dea...  Resilience
1    Albania’s PM announces end of operation launch...  Resilience
2    The search-and-rescue operation for earthquake...  Resilience
3    Rama said on Saturday that preliminary figures...    Building
4                     About 2,000 people were injured.  Resilience
..                                                 ...         ...
255  On 12 December, Italian Foreign Minister Luigi...       Other
256  Following the completion of the earthquake dam...       Other
257  A Post-Disaster Needs Assessment (PDNA) was es...       Other
258  On 10 January the EU announced that it had org...       Other
259  Apart from the EU and its member countries, de...       Other

[260 rows x 2 columns]

In [10]:
label

['Resilience',
 'Resilience',
 'Resilience',
 'Building',
 'Resilience',
 'Building',
 'Resilience',
 'Building',
 'Building',
 'Building',
 'Building',
 'Resilience',
 'Resilience',
 'Resilience',
 'Resilience',
 'Resilience',
 'Building',
 'Building',
 'Building',
 'Resilience',
 'Resilience',
 'Resilience',
 'Building',
 'Resilience',
 'Building',
 'Resilience',
 'Building',
 'Resilience',
 'Building',
 'Resilience',
 'Building',
 'Building',
 'Resilience',
 'Resilience',
 'Resilience',
 'Building',
 'Resilience',
 'Building',
 'Building',
 'Building',
 'Resilience',
 'Resilience',
 'Resilience',
 'Building',
 'Resilience',
 'Building',
 'Resilience',
 'Building',
 'Building',
 'Building',
 'Resilience',
 'Resilience',
 'Building',
 'Building',
 'Building',
 'Building',
 'Resilience',
 'Resilience',
 'Resilience',
 'Resilience',
 'Resilience',
 'Resilience',
 'Building',
 'Resilience',
 'Building',
 'Resilience',
 'Building',
 'Resilience',
 'Building',
 'Building',
 'Resilience',
 

In [11]:
df['CNN'] = label

In [12]:
df

sentence       label         CNN
0    Albania’s search for quake victims ends as dea...  Resilience  Resilience
1    Albania’s PM announces end of operation launch...  Resilience  Resilience
2    The search-and-rescue operation for earthquake...  Resilience  Resilience
3    Rama said on Saturday that preliminary figures...    Building    Building
4                     About 2,000 people were injured.  Resilience  Resilience
..                                                 ...         ...         ...
255  On 12 December, Italian Foreign Minister Luigi...       Other  Resilience
256  Following the completion of the earthquake dam...       Other  Resilience
257  A Post-Disaster Needs Assessment (PDNA) was es...       Other  Resilience
258  On 10 January the EU announced that it had org...       Other  Resilience
259  Apart from the EU and its member countries, de...       Other    Building

[260 rows x 3 columns]

In [13]:
confusion_matrix(df['label'], df['CNN'])

array([[30,  0,  0, 14],
       [ 1,  0,  0,  0],
       [31,  0,  0, 94],
       [22,  0,  0, 68]], dtype=int64)

In [14]:
df.to_csv('albania_CNN_predictions.csv')